<?php

/**
 * @file
 * Contains platform_paragraph.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function platform_paragraph_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the platform_paragraph module.
    case 'help.page.platform_paragraph':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Platform paragraph') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function platform_paragraph_theme() {
  return [
    'platform_paragraph' => [
      'render element' => 'children',
    ],
  ];
}
