<?php

/**
 * @file
 * Contains platform_paragraph.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tree_paragraph_collection_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the platform_paragraph module.
    case 'help.page.tree_paragraph_collection':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Tree paragraph collection') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tree_paragraph_collection_theme() {
  return [
    'tree_paragraph_collection' => [
      'render element' => 'children',
    ],
  ];
}
